version: '3.9'
services:
  api:
    build:
      context: .
    environment:
      - TELEMETRY_ENDPOINT=http://jaeger:4318/v1/traces
    ports:
    - "80:80"
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "4318:4318"
#      - "6831:6831"
#    environment:
#      - LOG_LEVEL=debug
