[tool.poetry]
name = "reasoner-validator"
version = "3.1.6"
description = "Validation tools for Reasoner API"
authors = ["Richard Bruskiewich, Patrick Wang"]
license = "MIT"
readme = "README.md"
packages = [{include = "reasoner_validator"}]

[tool.poetry.dependencies]
python = "^3.8"
kgx = "^1.6.0"
jsonschema = "^4.17.0"
PyYAML = "^6.0"
requests = "^2.28.1"
linkml-runtime = "^1.3.7"
linkml = "^1.3.14"
bmt = "^0.8.12"
fastapi = "^0.68"
pydantic = "^1.8.0"
uvicorn = "^0.15"

[tool.poetry.group.dev.dependencies]
pytest = "6.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
