name: Run tests
# Run tests at each push to master
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'pyproject.toml'
    - 'poetry.lock'
    - 'reasoner_validator/**'
    - 'tests/**'
    - '.github/workflows/test.yml'

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        poetry install -E web

    - name: Test with pytest with coverage
      run: |
        pytest --cov
